"""One-unit, quote-driven offline RL prototype with immutable chronological inputs."""

from copy import deepcopy
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal

from kiwit.marketdata.canonical import utc
from kiwit.ml.datasets import _hash

ACTIONS = ("NO_TRADE", "LONG", "SHORT", "EXIT")


def number(value):
    result = Decimal(str(value))
    if not result.is_finite():
        raise ValueError("Nonfinite value")
    return result


@dataclass(frozen=True)
class Costs:
    slippage: str = "0.0005"
    fee: str = "0.001"
    drawdown_penalty: str = "1"
    entry_penalty: str = "0.0001"

    def __post_init__(self):
        if any(number(v) < 0 for v in vars(self).values()):
            raise ValueError("Negative cost or penalty")
        if number(self.slippage) >= 1 or number(self.fee) >= 1:
            raise ValueError("Invalid execution costs")


class ShadowEnvironment:
    """Policy sees copied current features only. Tape/masks are trusted offline inputs.

    Long/short permission must be generated by an independent decision+risk pipeline.
    This simplified one-unit research model is not the production paper simulator.
    """

    def __init__(self, tape, *, capital="100000", costs=None):
        self._tape = deepcopy(tape)
        self.costs = costs or Costs()
        self.capital = number(capital)
        if self.capital <= 0 or len(tape) < 2:
            raise ValueError("Positive capital and at least two quotes required")
        last = None
        for row in self._tape:
            at = utc(datetime.fromisoformat(row["at"]))
            available = utc(datetime.fromisoformat(row["available_at"]))
            if available > at or (last is not None and at <= last):
                raise ValueError("Future or unordered observation")
            if not 0 < number(row["bid"]) <= number(row["ask"]):
                raise ValueError("Invalid executable quote")
            if not set(row["allowed_entries"]) <= {"LONG", "SHORT"}:
                raise ValueError("Invalid independent entry mask")
            if any(not isinstance(k, str) for k in row["features"]):
                raise ValueError("Feature names must be strings")
            for value in row["features"].values():
                if value is not None:
                    number(value)
            last = at
        self.i = None

    def reset(self):
        if self.i is not None and not self.done:
            raise ValueError("Cannot discard an unfinished episode")
        self.i, self.position = 0, 0
        self.entry = self.net = self.entry_fee = Decimal(0)
        self.peak = self.capital
        self.max_drawdown = self.reward_total = Decimal(0)
        self.entries = self.invalid = 0
        self.done = False
        self.events = []
        return self.observation()

    def observation(self):
        row = self._tape[self.i]
        mask = ["NO_TRADE"]
        if self.position:
            mask.append("EXIT")
        elif self.i < len(self._tape) - 2:
            mask.extend(row["allowed_entries"])
        return {
            "at": row["at"],
            "features": deepcopy(row["features"]),
            "position": self.position,
            "net_realized": str(self.net),
            "equity": str(self._equity(row)),
            "drawdown": str(self.max_drawdown),
            "action_mask": mask,
        }

    def _equity(self, row):
        if not self.position:
            return self.capital + self.net
        mark = number(row["bid"] if self.position == 1 else row["ask"])
        return self.capital + self.net + (mark - self.entry) * self.position - self.entry_fee

    def step(self, action):
        if self.i is None or self.done:
            raise ValueError("Reset required or episode completed")
        before = self._equity(self._tape[self.i])
        if action not in self.observation()["action_mask"]:
            self.invalid += 1
            action = "NO_TRADE"
        self.i += 1
        row = self._tape[self.i]
        slip, fee = number(self.costs.slippage), number(self.costs.fee)
        entered = 0
        if action in {"LONG", "SHORT"} and action in row["allowed_entries"]:
            side = 1 if action == "LONG" else -1
            price = number(row["ask"] if side == 1 else row["bid"]) * (1 + slip * side)
            if price * (1 + fee) <= before:
                self.position, self.entry, self.entry_fee = side, price, price * fee
                self.entries += 1
                entered = 1
        terminal = self.i == len(self._tape) - 1
        if self.position and (action == "EXIT" or terminal):
            price = number(row["bid"] if self.position == 1 else row["ask"]) * (1 - slip * self.position)
            self.net += (price - self.entry) * self.position - self.entry_fee - price * fee
            self.position = 0
        after = self._equity(row)
        self.peak = max(self.peak, after)
        drawdown = max(self.max_drawdown, (self.peak - after) / self.peak)
        reward = (
            (after - before) / self.capital
            - number(self.costs.drawdown_penalty) * (drawdown - self.max_drawdown)
            - number(self.costs.entry_penalty) * entered
        )
        self.max_drawdown = drawdown
        self.reward_total += reward
        self.done = terminal
        self.events.append({"at": row["at"], "action": action, "reward": str(reward), "equity": str(after)})
        return self.observation(), float(reward), self.done, {"shadow_only": True}

    def report(self):
        if not self.done:
            raise ValueError("Unsettled episode cannot be reported as completed")
        return {
            "net_pnl": str(self.net),
            "reward": str(self.reward_total),
            "maximum_drawdown": str(self.max_drawdown),
            "entries": self.entries,
            "invalid_actions": self.invalid,
            "events": deepcopy(self.events),
        }


def compare_shadow(tape, policies, *, training_end, evaluation_start, capital="100000", costs=None):
    """Run fixed candidate and champion policies on identical untouched supplied tape."""
    if set(policies) != {"candidate", "champion", "no_trade"}:
        raise ValueError("Candidate, champion and no_trade baselines required")
    if not utc(datetime.fromisoformat(training_end)) < utc(datetime.fromisoformat(evaluation_start)):
        raise ValueError("Training and evaluation must be disjoint")
    if any(utc(datetime.fromisoformat(row["at"])) < utc(datetime.fromisoformat(evaluation_start)) for row in tape):
        raise ValueError("Evaluation tape crosses held-out boundary")
    results = {}
    for name, policy in policies.items():
        env = ShadowEnvironment(tape, capital=capital, costs=costs)
        observation = env.reset()
        while not env.done:
            action = "NO_TRADE" if name == "no_trade" else policy(deepcopy(observation))
            observation, _, _, _ = env.step(action)
        results[name] = env.report()
    return {
        "version": "rl-shadow-prototype-v1",
        "tape_fingerprint": _hash(tape),
        "training_end": training_end,
        "evaluation_start": evaluation_start,
        "results": results,
        "promotion": "NOT_AUTHORIZED",
        "real_data_validated": False,
    }
